# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-atmos-terraform-drift-detection
  description: Atmos Terraform Drift Detection
  homepage: https://cloudposse.com/accelerate
  topics: ""
