name: "Test - PR comments"

on:
  pull_request: {}

env:
  AWS_REGION: us-east-2

# Permissions required for assuming AWS identity
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metadata-${{ github.run_id }}-test-pr-comments
          path: ./tests/fixtures/metadata
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Plan Atmos Component
        id: current
        uses: ./
        with:
          max-opened-issues: '4'
          labels: "test-pr-comments"
          token: ${{ github.token }}

    outputs:
      result: ${{ steps.current.outcome }}

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: 'success'
          actual: "${{ needs.test.outputs.result }}"

      - name: Count matching issues
        id: test
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              ...context.repo,
              labels: "test-pr-comments",
              state: "open",
              per_page: 100,
            });
            const count = issues.filter(issue => !issue.pull_request).length;
            core.info(`Count of found issues: ${count}`);
            core.setOutput("count", count);

      - uses: nick-fields/assert-action@v2
        with:
          expected: '4'
          actual: "${{ steps.test.outputs.count }}"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"

      - name: Close all matching issues
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              ...context.repo,
              labels: "test-pr-comments",
              state: "open",
              per_page: 100,
            });
            for (const issue of issues.filter(issue => !issue.pull_request)) {
              await github.rest.issues.update({
                ...context.repo,
                issue_number: issue.number,
                state: "closed",
              });
            }
