name: "Test - PR comments"

on:
  pull_request: {}

env:
  AWS_REGION: us-east-2

# Permissions required for assuming AWS identity
permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metadata-${{ github.run_id }}-${{ github.job }}
          path: ./tests/fixtures/metadata
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Plan Atmos Component
        id: current
        uses: ./
        with:
          max-opened-issues: '4'
          labels: "test-pr-comments"
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

    outputs:
      result: ${{ steps.current.outcome }}

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: 'success'
          actual: "${{ needs.test.outputs.result }}"

      - name: Find all issues
        id: issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-issues'
          token: ${{ github.token }}
          labels: 'test-pr-comments'
          issue-state: 'open'

      - name: Count found issues
        id: test
        run: |
          issue_count=$(echo '${{ steps.issues.outputs.issues }}' | jq '. | length')
          echo "Count of found issues: $issue_count"
          echo "count=$issue_count" >> $GITHUB_OUTPUT

      - uses: nick-fields/assert-action@v2
        with:
          expected: '4'
          actual: "${{ steps.test.outputs.count }}"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"

      - name: Close all matching issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ github.token }}
          labels: 'test-pr-comments'
