name: "Test - Changes exists - Drift"

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-2

# Permissions required for assuming AWS identity
permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: ./tests/fixtures/metadata
          retention-days: 1

      - name: Find all bugs
        id: bugs
        uses: lee-dohm/select-matching-issues@v1
        with:
          query: 'label:drift'
          token: ${{ github.token }}

      - name: Close found issues
        run: cat ${{ steps.bugs.outputs.path }} | xargs gh issue close

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Plan Atmos Component
        id: current
        uses: ./
        with:
          max-opened-issues: '3'
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

    outputs:
      result: ${{ steps.current.outcome }}

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'success'
          actual: "${{ needs.test.outputs.result }}"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
